name: Continuous Integration
on:
  pull_request:
    types: [opened, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub Repo
        uses: actions/checkout@v3
      - name: Setup Node/Npm
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Build App
        run: npm run build